#!/bin/bash

if [ $(id -u) -ne 0 ]; then
    sudo="sudo"
fi

$sudo docker ps | tail -n +2 | while read line; do
    cid=$(echo $line | awk '{print $NF}')
    ip=$($sudo docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${cid})
    printf "%-20s %s.docker\n" ${ip} ${cid}
    $sudo unbound-control local_data_remove "${cid}.docker." > /dev/null
    $sudo unbound-control local_data "${cid}.docker. 60 IN A ${ip}" > /dev/null
    $sudo unbound-control local_data "${ip} 60 ${cid}.docker." > /dev/null
done
