---
version: '3.4'
services:

  actions2:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - ../eduid-actions2/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=actions2"
      - "eduid_name=actions2"
      - "eduid_entrypoint=eduid_webapp.actions.run:app"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog
    extra_hosts:
      - "dashboard.eduid.docker:172.16.10.220"

  am:
    image: eduid-worker:latest
    networks:
      dev:
    volumes:
      - ../eduid-am/etc:/opt/eduid/eduid-am/etc:ro
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "HOSTNAME=am"
      - "ETCD_HOST=etcd.eduid_dev"
      - "eduid_name=am"
      - "celery_args=--loglevel DEBUG"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  authn:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - ../eduid-authn/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=authn"
      - "eduid_name=authn"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  dashboard_haproxy:
    image: 'docker.sunet.se/eduid/haproxy:latest'
    networks:
      dev:
        ipv4_address: 172.16.10.220
    volumes:
      - ../dashboard-haproxy/etc/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ../pki/dashboard.pem:/etc/ssl/dashboard.pem
      - /dev/log:/dev/log
    links:
      - authn
      - html
      - jsconfig
      - letter_proofing
      - lookup_mobile_proofing
      - oidc_proofing
      - orcid
      - personal_data
    depends_on:
      - authn
      - html
      - jsconfig
      - letter_proofing
      - lookup_mobile_proofing
      - oidc_proofing
      - personal_data

  eidas:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - ../eduid-eidas/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=eidas"
      - "eduid_name=eidas"
    depends_on:
      - am
      - etcd
      - mongodb
      - redis
      - rsyslog

  eidas_haproxy:
    image: 'docker.sunet.se/eduid/haproxy:latest'
    networks:
      dev:
        ipv4_address: 172.16.10.229
        aliases:
          - eidas.eduid.docker
    volumes:
      - ../eidas-haproxy/etc/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ../pki/eidas.pem:/etc/ssl/eidas.pem:ro
      - /dev/log:/dev/log
    depends_on:
      - eidas

  email:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.225
    expose:
      - 8080
    volumes:
      - ../eduid-email/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=email"
      - "eduid_name=email"
    depends_on:
      - redis
      - mongodb
      - etcd

  etcd:
    image: docker.sunet.se/library/etcd:v3.3.12
    expose:
      - 2379
      - 2380
      - 4001
    networks:
      dev:
        ipv4_address: 172.16.10.254
    command: >-
      etcd
      -name etcd
      -advertise-client-urls http://172.16.10.254:2379,http://172.16.10.254:4001
      -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
      -initial-advertise-peer-urls http://172.16.10.254:2380
      -listen-peer-urls http://0.0.0.0:2380
      -initial-cluster-token etcd-cluster-1
      -initial-cluster etcd=http://172.16.10.254:2380
      -initial-cluster-state new
      -data-dir /data
    volumes:
      - etcddata:/data

  feature_html:
    image: docker.sunet.se/eduid/eduid-html:latest
    expose:
      - 80
    dns: 172.16.10.1
    networks:
      dev:
        ipv4_address: 172.16.10.232
    volumes:
      - ../eduid-html/etc/html.conf:/etc/nginx/sites-enabled/html.conf:ro
      # source volumes
      - ../sources/eduid-html:/src/eduid/www:ro
      - ../sources/eduid-html/static:/src/eduid/static:ro
      - ../sources/eduid-front/build:/src/eduid/front-build:ro
    environment:
      - "HOSTNAME=feature-html"

  group_management:
    image: eduid-webapp:latest
    restart: on-failure
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - ../eduid-group-management/etc:/opt/eduid/etc
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=group_management"
      - "eduid_name=group_management"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  html:
    image: docker.sunet.se/eduid/eduid-html:latest
    expose:
      - 80
    dns: 172.16.10.1
    networks:
      dev:
        ipv4_address: 172.16.10.231
    volumes:
      # If you don't build JS bundles locally, leave html.conf out (and also sources/eduid-front/build below)
      - ../eduid-html/etc/html.conf:/etc/nginx/sites-enabled/html.conf:ro
      # source volumes
      - ../sources/eduid-html:/src/eduid/www:ro
      - ../sources/eduid-html/static:/src/eduid/static:ro
      - ../sources/eduid-front/build:/src/eduid/front-build:ro
    environment:
      - "HOSTNAME=html"

  html_haproxy:
    image: 'docker.sunet.se/eduid/haproxy:latest'
    networks:
      dev:
        ipv4_address: 172.16.10.230
        aliases:
          - html.eduid.docker
    volumes:
      - ../html-haproxy/etc/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ../pki/html.pem:/etc/ssl/html.pem:ro
      - /dev/log:/dev/log
    depends_on:
      - html
      - feature_html

  idp:
    image: eduid-webapp:latest
    networks:
      dev:
    volumes:
      - ../eduid-idp/etc:/opt/eduid/eduid-idp/etc:ro
      - appdata:/opt/eduid/eduid-idp/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
      - ../sources/pysaml2:/opt/eduid/src/pysaml2:ro
      - ../sources/pyXMLSecurity:/opt/eduid/src/pyXMLSecurity:ro
    environment:
      - "PYTHONPATH=/opt/eduid/src/pysaml2/src:/opt/eduid/src/pyXMLSecurity/src"
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=idp"
      - "eduid_name=idp"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog
      - vccs

  idp_haproxy:
    image: 'docker.sunet.se/eduid/haproxy:latest'
    networks:
      dev:
        ipv4_address: 172.16.10.200
        aliases:
          - idp.eduid.docker
    volumes:
      - ../idp-haproxy/etc/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ../pki/idp.pem:/etc/ssl/idp.pem:ro
      - /dev/log:/dev/log
    depends_on:
      - actions2
      - html
      - idp

  jsconfig:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - ../eduid-jsconfig/etc:/opt/eduid/etc:ro
      - ../pki/rootCA.crt:/etc/ssl/rootCA.crt:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "REQUESTS_CA_BUNDLE=/etc/ssl/rootCA.crt"
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=jsconfig"
      - "eduid_name=jsconfig"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  letter_proofing:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=letter_proofing"
      - "eduid_name=letter_proofing"
    depends_on:
      - am
      - etcd
      - mongodb
      - redis
      - rsyslog

  login_haproxy:
    image: 'docker.sunet.se/eduid/haproxy:latest'
    networks:
      dev:
        ipv4_address: 172.16.10.212
    volumes:
      - ../login-haproxy/etc/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ../pki/login.pem:/etc/ssl/login.pem:ro
      - /dev/log:/dev/log
    depends_on:
      - html
      - jsconfig
      - reset_password

  lookup-mobile:
    image: eduid-worker:latest
    networks:
      dev:
    volumes:
      - ../eduid-lookup-mobile/etc:/opt/eduid/eduid-lookup-mobile/etc:ro
      - appdata:/opt/eduid/eduid-lookup-mobile/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=lookup_mobile"
      - "eduid_name=lookup_mobile"
      - "celery_args=--loglevel DEBUG"
    depends_on:
      - mongodb
      - redis
      - rsyslog

  lookup_mobile_proofing:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=lookup_mobile_proofing"
      - "eduid_name=lookup_mobile_proofing"
    depends_on:
      - am
      - etcd
      - mongodb
      - redis
      - turq

  mongodb:
    image: docker.sunet.se/eduid/mongodb
    expose:
      - 27017
    networks:
      dev:
        ipv4_address: 172.16.10.253
    volumes:
      - mongodbdata:/data
      - ../mongodb/etc:/opt/eduid/etc:ro
      - ../mongodb/db-scripts:/opt/eduid/db-scripts:ro

  msg:
    image: eduid-worker:latest
    networks:
      dev:
    volumes:
      - ../eduid-msg/etc:/opt/eduid/eduid-msg/etc:ro
      - appdata:/opt/eduid/eduid-msg/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=msg"
      - "eduid_name=msg"
      - "celery_args=--loglevel DEBUG"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  neo4jdb:
    image: neo4j:4.0-enterprise
    expose:
      - 7474
      - 7687
    networks:
      dev:
        ipv4_address: 172.16.10.236
    volumes:
      - neo4jdbdata:/data
    environment:
      - "NEO4J_AUTH=neo4j/docker"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"

  oidc_proofing:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=oidc_proofing"
      - "eduid_name=oidc_proofing"
    depends_on:
      - am
      - etcd
      - mongodb
      - redis
      - rsyslog
      - turq

  orcid:
    image: eduid-webapp:latest
    networks:
      dev:
    expose:
      - 8080
    volumes:
      - ../eduid-orcid/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=orcid"
      - "LOCAL_CFG_FILE=/opt/eduid/etc/oidc_client_creds.yaml"
      - "eduid_name=orcid"
    depends_on:
      - am
      - etcd
      - mongodb
      - redis
      - rsyslog
      - turq

  personal_data:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.224
    expose:
      - 8080
    volumes:
      - ../eduid-personal-data/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=personal_data"
      - "eduid_name=personal_data"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  phone:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.226
    expose:
      - 8080
    volumes:
      - ../eduid-phone/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=phone"
      - "eduid_name=phone"
    depends_on:
      - etcd
      - mongodb
      - msg
      - redis
      - rsyslog

  py11softhsm:
    image: docker.sunet.se/eduid/py11softhsm
    networks:
      dev:
    expose:
      - 8000
    volumes:
      - softhsmdata:/var/lib/softhsm
      - /dev/log:/dev/log
      - ../sources/pyeleven:/opt/eduid/src/pyeleven:ro
      - ../py11softhsm/idp-public-snakeoil.key:/opt/eduid/idp-public-snakeoil.key:ro
    environment:
      - "PYTHONPATH=/opt/eduid/src/pyeleven/src"
      - "ENABLE_PKCS11_SPY=anything"
      - "p11softhsm_init_rsa_key=/opt/eduid/idp-public-snakeoil.key"

  redis:
    image: docker.sunet.se/eduid/redis
    expose:
      - 6379
    networks:
      dev:
        ipv4_address: 172.16.10.252
    volumes:
      - ../redis/etc:/etc/redis
      - redisdata:/data

  reset_password:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.213
    expose:
      - 8080
    volumes:
      - ../eduid-reset-password/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=reset_password"
      - "eduid_name=reset_password"
    depends_on:
      - etcd
      - mongodb
      - msg
      - redis
      - rsyslog
      - vccs

  rsyslog:
    image: docker.sunet.se/eduid/rsyslog
    expose:
      - 514
    networks:
      dev:
    volumes:
      - rsyslogdata:/var/log/eduid

  scimapi:
    image: eduid-falconapi:latest
    restart: on-failure
    networks:
      dev:
        ipv4_address: 172.16.10.235
    expose:
      - 8000
    volumes:
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "eduid_name=scimapi"
      - "eduid_entrypoint=eduid.scimapi.run:api"
      - "HOSTNAME=scimapi"
      - "ETCD_HOST=etcd.eduid_dev"
    depends_on:
      - mongodb
      - etcd
      - neo4jdb

  security:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.227
    expose:
      - 8080
    volumes:
      - ../eduid-security/etc:/opt/eduid/etc:ro
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=security"
      - "eduid_name=security"
    depends_on:
      - etcd
      - mongodb
      - msg
      - redis
      - rsyslog
      - vccs

  signup:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.211
    expose:
      - 8080
    volumes:
      - ../eduid-signup2/etc:/opt/eduid/etc
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=signup"
      - "eduid_name=signup"
    depends_on:
      - etcd
      - mongodb
      - msg
      - redis
      - rsyslog
      - vccs

  signup_haproxy:
    image: 'docker.sunet.se/eduid/haproxy:latest'
    networks:
      dev:
        ipv4_address: 172.16.10.210
    volumes:
      - ../signup-haproxy/etc/haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ../pki/signup.pem:/etc/ssl/signup.pem:ro
      - /dev/log:/dev/log
    depends_on:
      - html
      - jsconfig
      - signup

  support:
    image: eduid-webapp:latest
    networks:
      dev:
        ipv4_address: 172.16.10.223
    volumes:
      - appdata:/opt/eduid/run
      - eduidlogdata:/var/log/eduid
      # source volumes
      - ../sources/eduid-backend/src/eduid:/opt/eduid/src/eduid:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
      - "HOSTNAME=support"
      - "eduid_name=support"
    depends_on:
      - etcd
      - mongodb
      - redis
      - rsyslog

  turq:
    image: docker.sunet.se/eduid/turq
    networks:
      dev:
        ipv4_address: 172.16.10.250

  vccs:
    image: 'docker.sunet.se/eduid/eduid-vccs2:latest'
    restart: always
    networks:
      dev:
        ipv4_address: 172.16.10.238
    expose:
      - 8080
    volumes:
      - eduidlogdata:/var/log/eduid
      - ../vccs:/opt/eduid/vccs:ro
      - ../sources/VCCS2/:/opt/eduid/src/VCCS2:ro
    environment:
      - "PYTHONPATH=/opt/eduid/src/VCCS2/src:/opt/eduid/src/eduid-userdb/src:/opt/eduid/src/eduid-common/src:/opt/eduid/VCCS2/src"
      - "EDUID_CONFIG_YAML=/opt/eduid/vccs/config.yaml"


  # Update config in etcd on each restart
  update_etcd:
    image: 'docker.sunet.se/eduid/eduid-webapp:latest'
    networks:
      dev:
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /opt/eduid/src/eduid-developer/etcd:/etcd:ro
    environment:
      - "ETCD_HOST=etcd.eduid_dev"
    links:
      - etcd
    depends_on:
      - etcd
    working_dir: /etcd
    entrypoint: "sh -c 'sleep 1; /opt/eduid/bin/python3 /etcd/etcd_config_bootstrap.py'"


volumes:
  appdata:
    name: appdata
  eduidlogdata:
    name: eduidlogdata
  etcddata:
    name: etcddata
  mongodbdata:
    name: mongodbdata
  neo4jdbdata:
    name: neo4jdbdata
  redisdata:
    name: redisdata
  rsyslogdata:
    name: rsyslogdata
  softhsmdata:
    name: softhsmdata



networks:
  dev:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-eduid
    ipam:
      driver: default
      config:
      - subnet: 172.16.10.0/24
