#!/usr/bin/env python3
#
# Remove all managed accounts by dropping the collection containing them.
#

import sys
from eduid.userdb.admin import RawDb, get_argparser

def main(args):
    """
    Remove all managed accounts by dropping the collection containing them.
    """
    db = RawDb()

    coll = db._client['eduid_managed_accounts']['users']

    print(f'Removing {coll.count_documents({})} managed users')
    if args.force:
        coll.drop()

if __name__ == '__main__':
    parser = get_argparser(description='Remove all managed accounts')
    args = parser.parse_args()

    if args.debug:
        print(f"{'Dry run' if not args.force else 'For real'}")
    main(args)
    sys.exit(0)
