---
mongo_databases:

  admin:
    collections: []
    access:
      root:
        - 'admin'
      backup:
        - 'backup'
      clusterMonitor:
        - 'nagios'

  eduid_am:
    collections:
      - 'attributes'
    access:
      readWrite:
        - 'eduid_am'
        - 'eduid_amapi'
      read:
        - 'eduid_actions'
        - 'eduid_authn'
        - 'eduid_dashboard'
        - 'eduid_eidas'
        - 'eduid_email'
        - 'eduid_idp'
        - 'eduid_idproofing_letter'
        - 'eduid_lookup_mobile_proofing'
        - 'eduid_oidc_proofing'
        - 'eduid_orcid'
        - 'eduid_personal_data'
        - 'eduid_phone'
        - 'eduid_reset_password'
        - 'eduid_scimapi'
        - 'eduid_security'
        - 'eduid_signup'
        - 'eduid_support'
        - 'eduid_group_management'
        - 'eduid_ladok'
        - 'eduid_svipe_id'
        - 'eduid_bankid'
        - 'eduid_freja_eid'
        - 'munin'
        - 'eduid_job_runner'
        - 'eduid_samleid'

  eduid_api:
    collections:
      - 'users'
    access:
      readWrite:
        - 'eduid_api'
        - 'eduid_oathaead'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_idp:
    collections:
      - 'authn_info'
      - 'sso_sessions'
    access:
      readWrite:
        - 'eduid_idp'
      read:
        - 'eduid_support'

  eduid_idp_pysaml2:
    collections:
      - 'ident'
      - 'session'
    access:
      readWrite:
        - 'eduid_idp'
        - 'eduid_support'  # XXX probably not needed

  eduid_msg:
    collections:
      - 'navet_cache'
      - 'recipient_cache'
      - 'transaction_audit'
    access:
      readWrite:
        - 'eduid_msg'

  eduid_signup:
    collections:
      - 'registered'
      - 'invites'
    access:
      readWrite:
        - 'eduid_signup'
        - 'eduid_scimapi'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_tou:
    collections:
      - 'consent'
    access:
      readWrite:
        - 'eduid_signup'
        - 'eduid_actions'
      read:
        - 'eduid_support'

  eduid_dashboard:
    collections:
      - 'profiles'
      - 'reset_passwords'
      - 'verifications'
      - 'wizards'
    access:
      readWrite:
        - 'eduid_dashboard'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_idp_authninfo:
    collections:
      - 'authn_info'
    access:
      readWrite:
        - 'eduid_idp'
      read:
        - 'eduid_dashboard'
        - 'eduid_support'
        - 'eduid_security'

  eduid_lookup_mobile:
    collections:
      - 'transaction_audit'
    access:
      readWrite:
        - 'eduid_lookup_mobile'
      read:
        - 'eduid_support'

  eduid_actions:
    collections:
      - 'actions'
    access:
      readWrite:
        - 'eduid_actions'
        - 'eduid_idp'
        - 'eduid_am'
      read:
        - 'eduid_support'

  eduid_idproofing_letter:
    collections:
      - 'proofing_data'
    access:
      readWrite:
        - 'eduid_idproofing_letter'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_ladok:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_ladok'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_oidc_proofing:
    collections:
      - 'profiles'
      - 'proofing_data'
      - 'proofs'
    access:
      readWrite:
        - 'eduid_oidc_proofing'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_orcid:
    collections:
      - 'profiles'
      - 'proofing_data'
    access:
      readWrite:
        - 'eduid_orcid'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_eidas:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_eidas'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_lookup_mobile_proofing:
    collections:
      - 'profiles'
      - 'proofing_data'
    access:
      readWrite:
        - 'eduid_lookup_mobile_proofing'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_email:
    collections:
      - 'profiles'
      - 'proofing_data'
    access:
      readWrite:
        - 'eduid_email'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_security:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_security'
      read:
        - 'eduid_am'

  eduid_reset_password:
    collections:
      - 'profiles'
      - 'password_reset_data'
    access:
      readWrite:
        - 'eduid_reset_password'
      read:
        - 'eduid_am'

  eduid_personal_data:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_personal_data'
      read:
        - 'eduid_am'

  eduid_phone:
    collections:
      - 'profiles'
      - 'proofing_data'
    access:
      readWrite:
        - 'eduid_phone'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_scimapi:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_scimapi'
        - 'eduid_group_management'
      read:
        - 'eduid_idpproxy'

  eduid_group_management:
    collections:
      - 'group_invite_data'
    access:
      readWrite:
        - 'eduid_group_management'
      read:
        - 'eduid_support'

  eduid_svipe_id:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_svipe_id'
      read:
        - 'eduid_support'

  eduid_freja_eid:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_freja_eid'
      read:
        - 'eduid_support'

  eduid_logs:
    collections:
      - 'proofing_log'
    access:
      readWrite:
        - 'eduid_oidc_proofing'
        - 'eduid_idproofing_letter'
        - 'eduid_lookup_mobile_proofing'
        - 'eduid_email'
        - 'eduid_phone'
        - 'eduid_security'
        - 'eduid_reset_password'
        - 'eduid_orcid'
        - 'eduid_signup'
        - 'eduid_eidas'
        - 'eduid_ladok'
        - 'eduid_svipe_id'
        - 'eduid_bankid'
        - 'eduid_maccapi'
        - 'eduid_freja_eid'
        - 'eduid_job_runner'
        - 'eduid_samleid'
      read:
        - 'eduid_support'

  eduid_queue:
    collections:
      - 'messages'
    access:
      readWrite:
        - 'eduid_queue'
        - 'eduid_scimapi'
        - 'eduid_signup'
        - 'eduid_reset_password'
        - 'eduid_email'
        - 'eduid_security'

  seleg_op:
    collections:
      - 'access_tokens'
      - 'authn_requests'
      - 'authz_codes'
      - 'clients'
      - 'refresh_tokens'
      - 'subject_identifiers'
      - 'userinfo'
    access:
      readWrite:
        - 'op'

  eduid_auth_server:
    collections:
      - 'transaction_states'
      - 'saml_authentications_cache'
      - 'pysaml2_identity_cache'
      - 'pysaml2_outstanding_queries'
      - 'pysaml2_state_cache'
    access:
      readWrite:
        - 'eduid_auth_server'

  eduid_bankid:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_bankid'
      read:
        - 'eduid_am'
        - 'eduid_support'

  eduid_idpproxy:
    access:
      readWrite:
        - 'eduid_idpproxy'

  eduid_managed_accounts:
    collections:
      - 'users'
    access:
      readWrite:
        - 'eduid_maccapi'
      read:
        - 'eduid_idp'

  eduid_job_runner:
    collections:
      - 'cleaner_queue'
    access:
      readWrite:
        - 'eduid_job_runner'

  eduid_samleid:
    collections:
      - 'profiles'
    access:
      readWrite:
        - 'eduid_samleid'
      read:
        - 'eduid_am'
        - 'eduid_support'

