#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Remove users that have asked to terminate their account more than seven days ago.
#
# Run as:
#
#   run_with_admintools /opt/eduid/db-scripts/remove-terminated-users
#

from datetime import datetime, timedelta

import pymongo.errors
import sys

from eduid.userdb.admin import RawDb, get_argparser

KEEP_USER_DAYS = 7


def remove_from_aux_db(db, dry_run, _id, db_name, coll_name, key='_id'):
    for raw in db.find(db_name, coll_name, {key: _id}):
        raw.doc['DELETE_DOCUMENT'] = True
        db.save_with_backup(raw, dry_run=dry_run)


def main(dry_run):
    db = RawDb(myname='remove-terminated-users')

    terminated_before = datetime.today() - timedelta(days=KEEP_USER_DAYS)
    for raw_user in db.find(
        'eduid_am',
        'attributes',
        {'$and': [{'terminated': {'$exists': True}}, {'terminated': {'$lt': terminated_before}}]},
    ):
        print('{} {}'.format(raw_user.doc.get('eduPersonPrincipalName'), raw_user.doc.get('terminated')))

        _id = raw_user.doc['_id']
        remove_from_aux_db(db, dry_run, _id, 'eduid_idp_authninfo', 'authn_info')
        remove_from_aux_db(db, dry_run, _id, 'eduid_idp_pysaml2', 'ident', key='user_id')
        remove_from_aux_db(db, dry_run, _id, 'eduid_tou', 'consent', key='user_id')
        remove_from_aux_db(db, dry_run, _id, 'eduid_signup', 'registered')
        remove_from_aux_db(db, dry_run, _id, 'eduid_dashboard', 'profiles')
        remove_from_aux_db(db, dry_run, _id, 'eduid_dashboard', 'verifications', key='user_oid')
        remove_from_aux_db(db, dry_run, _id, 'eduid_dashboard', 'wizards', key='userid')

        raw_user.doc = {
            '_id': raw_user.doc['_id'],
            'eduPersonPrincipalName': raw_user.doc['eduPersonPrincipalName'],
        }
        db.save_with_backup(raw_user, dry_run=dry_run)

    return True


if __name__ == '__main__':
    parser = get_argparser(description='Permanently remove terminated users')
    parser.add_argument(
        '--ignore-not-master',
        dest='ignore_not_master',
        action='store_true',
        default=False,
        help='Ignore errors about not running on mongodb master',
    )
    args = parser.parse_args()

    print('Dry run: {}'.format(not args.force))
    try:
        if main(not args.force):
            sys.exit(0)
    except pymongo.errors.AutoReconnect:
        if args.ignore_not_master:
            print('Not running on database master - ignoring')
            sys.exit(0)
        raise
    sys.exit(1)
